debug: false

Setting:
  language: "korean"
  cluck-type: RIGHT
  log: true

Pet:
  allow-duplicates: true
  use-category: true
  use-chance: true

  item:
    material: ENCHANTED_BOOK
    display-name: "&7&l펫 뽑기권"
    lore:
      - "  &8[설명] &7사용 시 해당 펫을 획득합니다."
      - "  &8[사용] "
    model-data: -1

Sound:
  # sound setting: "soundName, volume, pitch"
  success:
    - "minecraft:entity.player.levelup, 1, 1"
  fail:
    - "minecraft:ui.button.click, 1, 1"